-- OPERADORES LÓGICOS
-- ALL ANY/SOME

-- RETURN ONLY THE EMPLOYEES FROM THE 40 DEPARTMENT WHO HAVES A BIGGEST SALARY THEN ALL THE 
-- EMPLOYEES FROM THE 30 DEPARTMENT

-- WITH ALL + SUBQUERY

-- WITH > + SUBQUERY