-- COLUMN ATTRIBUTES

-- COLUMN NAME
-- ** FOR EACH COLUMN WE CAN SPECIFY A NAME TO COLUMN TO UNIQUELY INDETIFY EACH COLUMN FROM A TABLE **

-- DATA TYPE
-- ** LIKE OTHER PROGRAMMING LANGUAGES WE HAVE ALSO IN SQL DATA TYPES TO BE INSERTED IN EACH COLUMN IN A TABLE
-- FOR ISTANCE WE HAVE:
-- CHAR(size)
-- VARCHAR(size)
-- INTEGER(size)
-- AND SO ON...... **

-- CONSTRAIN TYPE
-- ** WE CAN ALSO GIVE CONSTRAINS FOR EACH COLUMN FROM A TABLE, FOR INSTANCE WE CAN UNIQUE INDENTIFY EACH VALUE FROM A COLUMN
-- WITH UNIQUE CONSTRAIN OR WITH PRIMARY KEY TO SPECIFY AS AN MAIN KEY OF THE TABLE **

-- DEFAULT/EXPRESSION VALUE
-- ** COLUMNS CAN ALSO HAVE DEFAULT VALUES WHEN ISN´T INSERT WHEN VALUE WITH INSERT INTO STATMENT
-- FOR INSTANCE IF WE SET DEFAULT VALUE WAS NULL, BY DEFAULT THE VALUES WILL BE NULL IF THERE ISN´T ANY VALUE INSERT INTO**