-- CROSS JOINS

-- ** WITH CROSS JOINS WE CAN COMBINE ALL RECORDS FROM TABLE WITH ANOTHER TABLE

-- LET´S SEE A PRACTICE EXAMPLE

-- DO A CROSS JOIN BETWEEN SHIPPERS AND PRODUCTS
-- USING THE IMPLICIT SYNTAX 
-- AND THEN USING THE EXPLICIT SYNTAX

-- IMPLICIT SYNTAX
SELECT sh.name AS shipper, p.name AS product
FROM shippers AS sh, products AS p
ORDER BY sh.name;

-- EXPLICIT SYNTAX
SELECT sh.name AS shipper, p.name AS product
FROM shippers AS sh
CROSS JOIN products AS p
ORDER BY sh.name;