-- INSERT INTO in multiple tables
-- INSERT DATA INTO MULTIPE TABLES
SELECT * FROM orders;
SELECT * FROM order_items;

-- LET´S SEE SOME EXAMPLES:
-- FIRST WE INSERT INTO THE PARENT TABLE ORDERS A NEW RECORD FOR THE ORDERS
INSERT INTO orders(customer_id,order_date,status)
VALUES(1, '2019-01-02',1);

-- TO CHECK THE LAST INSERTED ID 
-- SELECT LAST_INSERT_ID()

-- THAN WE INSERT INTO THE CHILD TABLE 2 NEW RECORDS FOR THE ORDER ITEMS WITH THE LAST ID INSERTED
INSERT INTO order_items
VALUES (LAST_INSERT_ID(),1,1,2.95),
		(LAST_INSERT_ID(),2,1,3.95);

	-- NOTICE THAT WITH THE LAST INSERT ID FUNCTION WILL RETURN 2 RECORDS WITH THE SAME LAST ID
	-- IN THE ORDER_ID